language: python
python:
  - "2.7"
  - "3.5"


before_install:
  - pip install cython
  - pip install coverage
  - pip install coveralls  
  - python setup_coverage.py build_ext --inplace


# command to run tests
script: coverage run setup_coverage.py nosetests

after_success: coveralls || echo "Coveralls upload failed"