package:
  name: sparsearray
  version: "0.8.15"

requirements:
  build:
    - python
    - cython
    - setuptools

  run:
    - python

test:
    requires:
        - nose
        - numpy
        - cython
    imports:
        - SparseArray
    commands:
        - nosetests --exe SparseArray

about:
  home: https://github.com/INGEOTEC/SparseArray
  summary: SparseArray
  license: Apache
